### ISSUE TITLE
Request:  Might be nice to have a copy project and rename project function.

### ISSUE THREAD

**Issue by hathawayj** [JasperHG90/qualtRics#11]
Sometimes I build a project survey and then I want to use the same survey for a different group or project.  It can get tedious to point an click.  Thanks.

**Comment by JasperHG90** [comment]
I'm not sure what it is you're asking me. This is not an official package and I am not affiliated with Qualtrics.

**Comment by hathawayj** [comment]
Well, now I don't remember either.  Must have been a late night comment.
