### ISSUE TITLE
too many columns error

### ISSUE THREAD

**Issue by vince-p** [JasperHG90/qualtRics#13]
When using the getSurvey function I get the following error for one particular survey:

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
```

I don't know how to debug this error. Any suggestions?

**Comment by JasperHG90** [comment]
Hey Vince, 

Sorry for this late response. Somehow missed this question.

That error indicates that there are more columns than header names in your survey. This error frequently occurs when the CSV isn't properly escaped and so, when loading the data into R, R thinks there's an extra column while there is none.

If at all possible, could I get access to your data set? I've not seen this error before and am curious when it occurs.

Best,

Jasper.

**Comment by JasperHG90** [comment]
@vince-p : could you review my response? I'd like to resolve this issue for you and others!

**Comment by vince-p** [comment]
Sorry I dont have access that particular survey anymore, but I think this was caused by me changing a question in Qualtrics after some data had already been collected. So some of the early records had data in a column that was no longer present for the later records.

**Comment by JasperHG90** [comment]
Ah, that makes sense. Thanks for letting me know!
