### ISSUE TITLE
Lag time? Doesn't seem to be updating?

### ISSUE THREAD

**Issue by ValorNVirtue** [JasperHG90/qualtRics#16]
R newbie here.

Made changes to the survey in Qualtrics, changes not observed when I run the script in R.  Is there a lag between making updates in Qualtrics and downloading the data using this package?

**Comment by JasperHG90** [comment]
There is in the development version on GitHub. Surveys are stored in the R temporary directory. In version <=0.3 this isn't the case. Could you try restarting your R session? If the problem is due to qualtRics, a fresh download of your survey should reflect the changes you made.

**Comment by ValorNVirtue** [comment]
I was able to install the development version from GitHub and have restarted the session a few times now and still the same problem.  I also tried changing the directory to my desktop, changed the API key in Qualtrics and updated in R, and I'm still having the same issue.

**Comment by JasperHG90** [comment]
I've been trying this on some of my own surveys, and it seems that this is a feature of the qualtrics API. I'm not exactly sure how much time must past before you can make a new request or whether you can force another request. Thanks for notifying me about this; I'll see if I can force a new export when needed.

You're welcome.

**Comment by ValorNVirtue** [comment]
Just got off the phone with Qualtrics.

API requests are dependent on the number of requests at the time.  Most
delays between new data in Qualtrics and the API request are a* matter of
seconds, rarely minutes*.

There are two different versions of the API request, so it depends on the
number of calls at the time per the request.

Also, the API request can be cached, so if a new request is made, it could
be the cached version if the new API request has not yet been processed.
Support said to clear cookies, try a different browser, or in our case,
clear the temp dir by restarting the R session (as you suggested).

He's going to test a few different requests on his end and try to get an
estimate of that latency for me.  If I hear back from him I'll update this
thread to give other users an idea.

Respectfully,
--
AJ Thurston

University of South Florida
Doctoral Student, Industrial & Organizational Psychology

4202 E. Fowler Avenue, PCD4118G

Tampa, Florida 33620

Office: PCD3120A

**Comment by JasperHG90** [comment]
Have you heard anything from them?

**Comment by ValorNVirtue** [comment]
I did not, but I tested it myself and found a delay of maybe a minute at
most.

Respectfully,
--
AJ Thurston

University of South Florida
Doctoral Student, Industrial & Organizational Psychology

4202 E. Fowler Avenue, PCD4118G

Tampa, Florida 33620

Office: PCD3120A

**Comment by JasperHG90** [comment]
Thanks!
