### ISSUE TITLE
Avoiding API#

### ISSUE THREAD

**Issue by ndyetz** [JasperHG90/qualtRics#20]
Hi Jasper, 

Thanks for creating this tool.

Is it possible to avoid the API Number or get around it? I would love to be able to use this but my organization does not have access to our API numbers in the Qualtrics platform, thus limiting my ability to use this tool.

Thank you. 
Neil

**Comment by JasperHG90** [comment]
Hi Neil,

Thanks for your message. Unfortunately, you must have access to the Qualtrics API to use most functions in this package. However, it is possible to manually download surveys and read them into R using the `readSurvey()` function.

Best,

J.

**Comment by ndyetz** [comment]
Thank you, Jasper!

Looking to get to gain access to that API number. Regardless, this has the
potential to save me so much time.
Thanks for creating this! Much Appreciated.

Cheers,
Neil

*Neil Yetz, MPH Candidate*
Graduate Research Assistant
Department of Psychology & Colorado School of Public Health
Colorado State University
