### ISSUE TITLE
REQUEST: append date to filename

### ISSUE THREAD

**Issue by vince-p** [JasperHG90/qualtRics#23]
When saving a rds file through the getSurvey function, could you add an option to append the date/time to the filename.

**Comment by JasperHG90** [comment]
Hi Vince,

Thanks for your response. Just out of interest: why do you want this option?

J.

**Comment by vince-p** [comment]
To help with reproducability. This would make it easier to supply a specific dataset (from a specific time) and code to another person.

**Comment by JasperHG90** [comment]
Unless I get more requests for this feature I won't implement it because this use case is quite specific and it's straightforward to implement this yourself using e.g. the following function:

```r
# Save dataset with date/time info
saveSurveyDT <- function(surveyID, root_url, location) {
  surv <- getSurvey(surveyID,
                    root_url = root_url,
                    convertStandardColumns = FALSE,
                    useLabels = TRUE,
                    verbose = TRUE)
  # Save as RDS
  saveRDS(surv, paste0(location, "/", surveyID, "_", as.character(as.integer(Sys.time())), ".rds"))
}
```

Hope that helps.

Best,

J.
