### ISSUE TITLE
Warning about sjmisc

### ISSUE THREAD

**Issue by Delkine** [JasperHG90/qualtRics#25]
Thank you for Providing qualtRics to download survey information and responses.  It is really a great tool. I've recently started getting this "Warning message:
This function will be removed in future versions of sjmisc and has been moved to package 'sjlabelled'. Please use sjlabelled::set_label() instead."

How will this affect how we use qualtRics?  Will we need to do something different when downloading survey responses?
Thank you!

**Comment by JasperHG90** [comment]
Hi Delkine,

Thanks for your message.

I've already made this change on the master branch of this repository. It will be released on CRAN soon, which should remove this error.

Best,

Jasper.
