### ISSUE TITLE
Error when running script in taskscheduleR

### ISSUE THREAD

**Issue by Delkine** [JasperHG90/qualtRics#26]
When I run my script following your examples from Rstudio I have no problem getting the script to run and create a *.csv file with the responses to my survey.  However when I try to automate its execution and run it from taskscheduleR as an Addin called from Rstudion I get the following error message in the log file and I get no output.  Can you help me fix this.  Other scripts I run work just fine using the same process.

"Installing package into 'C:/Users/del/Documents/R/win-library/3.4'
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted"

Thank you!

Del

**Comment by JasperHG90** [comment]
Hi Del,

Thanks for your message.

That error occurs because you haven't set a CRAN mirror. See https://stackoverflow.com/questions/11488174/how-to-select-a-cran-mirror-in-r. 

I'm closing this issue because it is not related to the qualtRics package.

Best,

Jasper.
