### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Delkine** [JasperHG90/qualtRics#27]
Beginning Saturday I began experiencing problems running qualtRics that I had never seen before.  I checked your documentation and it looks like you have implemented some new features and made several changes.  It looks like the changes will be nice improvements but for now I'm having issues that I can't find any documentation about. I installed your latest version of qualtRics.  I have created registerOptions () file and placed it in my wd.   When I run my whole script I get several errors.  It appears that the regiserOptions file is not being read.  When I put enter my API token and root_url directly in the registerOptions() command it seems to work now.

**Comment by JasperHG90** [comment]
Thanks for your message! Could you post a screenshot of the error here or PM it to me?

**Comment by JasperHG90** [comment]
Given that I can't see what went wrong here's a couple of generic tips:

1. Use the 'qualtRicsConfigFile()' to get instructions on how o make the configuration file.
2. The config file should be called '.qualtRics.yml' 
3. You should store this file in the working directory. The WD changes every time you start a new R project.

**Comment by Delkine** [comment]
I meant it appeared as if the .qualtRics.yml file was not being read.  I have since got it to work if I have the token and root_url in the registerOptions() file.  I get a message that the yml file was found.
