### ISSUE TITLE
Include question label in output of getSurveyQuestions()

### ISSUE THREAD

**Issue by vince-p** [JasperHG90/qualtRics#35]
It would be great to also have a column showing the question label for each item.
I.e., include:
QID
Question Label
Question Text

This is a really handy function - thanks!

**Comment by JasperHG90** [comment]
Hi Vince,

Thanks for your request. I'll see if that's included in the result!

Best,

Jasper.

**Comment by KAnalytics** [comment]
Hi Jasper,

It seems like the question label using getSurvey() is slightly different than using getSurveyQuestions(). I think this affects matrix based questionnaires that have many sub-questions.

Thanks,

Kai

**Comment by JasperHG90** [comment]
@phoebewong fixed this.
