### ISSUE TITLE
Unknown Warning

### ISSUE THREAD

**Issue by Delkine** [JasperHG90/qualtRics#38]
I'm receiving the following warning when I us qualtRics to download a survey.  
"Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  invalid input found on input connection 'C:/Users/del/AppData/Local/Temp/RtmpQZ7nvM/Mindshare English v21.csv'"

Can you point me some help with this?  I'm also not getting all the respondent surveys in the download.

Del

**Comment by JasperHG90** [comment]
Hi Del,

Thanks for your message. I think this error is the same as #36. 

As you can see from that thread, it's quite difficult for me a) reproduce this error on my end and b) debug it at a distance.

Would you be open to skyping and sharing your screen with me so I can see the exact steps you're taking? It would speed up the debugging process.

If not, then we'll try to do this at a distance.

Thanks for considering!

J.

**Comment by Delkine** [comment]
I'm happy to do  Skype with you but not today.  I'm in California and by the time  I get home it will be too late.   Can you do it tomorrow?
Del

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jasper Ginn <notifications@github.com> Date: 7/4/17  10:29 AM  (GMT-08:00) To: JasperHG90/qualtRics <qualtRics@noreply.github.com> Cc: Delkine <dnebeker@cox.net>, Author <author@noreply.github.com> Subject: Re: [JasperHG90/qualtRics] Unknown Warning (#38) 
Hi Del,
Thanks for your message. I think this error is the same as #36.
As you can see from that thread, it's quite difficult for me a) reproduce this error on my end and b) debug it at a distance.
Would you be open to skyping and sharing your screen with me so I can see the exact steps you're taking? It would speed up the debugging process.
If not, then we'll try to do this at a distance.
Thanks for considering!
J.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JasperHG90/qualtRics","title":"JasperHG90/qualtRics","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JasperHG90/qualtRics"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JasperHG90 in #38: Hi Del,\r\n\r\nThanks for your message. I think this error is the same as #36. \r\n\r\nAs you can see from that thread, it's quite difficult for me a) reproduce this error on my end and b) debug it at a distance.\r\n\r\nWould you be open to skyping and sharing your screen with me so I can see the exact steps you're taking? It would speed up the debugging process.\r\n\r\nIf not, then we'll try to do this at a distance.\r\n\r\nThanks for considering!\r\n\r\nJ."}],"action":{"name":"View Issue","url":"https://github.com/JasperHG90/qualtRics/issues/38#issuecomment-312923641"}}}

**Comment by JasperHG90** [comment]
Hi Del,

Thanks for your reply. I'm in the Netherlands so I I'm 9 hours ahead of you. 

Let me know which times work for you! I'm available pretty much all day today and tomorrow with any time before 2pm and 9pm your time.

Best,

J.

**Comment by Delkine** [comment]
Hi Jasper,

 

Thanks for your help!  I have found that the culprit is probably  emojis entered by respondents who are likely using a smartphone or tablet.  I’ve been trying to get help from Qualtrics about preventing these or deleting them automatically but so far I haven’t spoken to the right person.  Is there anything you can do to make these characters legitimate?

 

Del

**Comment by JasperHG90** [comment]
Hi Del.

I was able to reproduce the error on Windows in a virtual machine (left). Interestingly, the error does not occur on OSx. 

![warning](https://user-images.githubusercontent.com/8079803/27899135-4669bbc0-6229-11e7-9070-c9d61f8501e6.png)

Probably something to do with encoding used in 'readSurvey()'. I'll get back to you with some solutions!

Thanks!

J.

**Comment by JasperHG90** [comment]
Found the reason for this error. readSurvey() [uses](https://github.com/JasperHG90/qualtRics/blob/development/R/readSurvey.R#L65) 'UTF-8-BOM' as encoding.

**Comment by JasperHG90** [comment]
Hi Del,

Changing the fileEncoding argument in readSurveys() solved the problem. fileEncoding is now an optional argument for getSurvey() and the default should work on Windows (left) and OSx (right)

![warningsolved](https://user-images.githubusercontent.com/8079803/27900425-9b88d9ce-622e-11e7-9d60-9bc2d28fc220.png)

Please execute the following code and check if it works for you:

```r
# Install qualtRics
devtools::install_github("JasperHG90/qualtRics", ref="development")

# Load qualtrics
library(qualtRics)

# Get surveys
survs <- getSurveys()

# Get survey
surv <- getSurvey(<YOUR-SURVEY-ID>)
```

**Comment by Delkine** [comment]
Jasper,

 

Thank you.  It seems to be working fine now. 

 

Del
