### ISSUE TITLE
Question on "registerOptions"

### ISSUE THREAD

**Issue by shiyaoliu** [JasperHG90/qualtRics#39]
When I tried to initialize the registerOptions, it pops up "Error: assert_that: assertion must return a logical value"

Code:
registerOptions(api_token="[token with length of 40]",
                    root_url="mit.co1.qualtrics.com")

Thanks!

**Comment by JasperHG90** [comment]
Hi Shiyaoliu,

Thanks for your message.

I cannot reproduce this error. Could you please do the following:

1. Re-run your exact steps and post them here.
2. In the R console, run 'sessionInfo()'. Copy-paste the results in this thread.

Thanks,

J.

**Comment by shiyaoliu** [comment]
Hi Jasper,

After I post the issue here, I upgraded all packages installed on my R. The error seemed to disappear.

Thank you very much.
