### ISSUE TITLE
Get contact lists?

### ISSUE THREAD

**Issue by KAnalytics** [JasperHG90/qualtRics#40]
Hi Jasper,

Thanks for building this package for us R users.
I was wondering if there are any plans to implement a way to get contact list to a particular survey?

Sincerely,

Kai

**Comment by JasperHG90** [comment]
Hi Kai,

Thanks for your message. I'm glad the package is useful to you.

My focus lies primarily on pulling in survey results. I currently don't have any plans to implement the feature you're requesting. It shouldn't be too hard to write a function that does this for your personal use though. All you really need are the [utils](https://github.com/JasperHG90/qualtRics/blob/master/R/utils.R) and [assertions](https://github.com/JasperHG90/qualtRics/blob/master/R/assertions.R) files and a base url end point (you can find this in the [qualtrics documentation](https://api.qualtrics.com/docs/get-distribution)).

All the best,

J.
