### ISSUE TITLE
Possible Encoding Issue with Windows 10

### ISSUE THREAD

**Issue by shiyaoliu** [JasperHG90/qualtRics#41]
Hi Jasper,

I tried to getSurvey from my qualtrics, but got the following error message. My platform is Windows 10 Professional Simplified Chinese. The same code works under Ubuntu 16.04 LTS. So I guess it's probably an encoding issue.

Thanks.

Best,
Sean

> mysurvey.2 <- getSurvey(surveyID = surveys$id[2])
  |======================================================================================| 100%
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning messages:
1: In readLines(file, skip) :
  invalid input found on input connection '.../China Survey.csv'
2: In readLines(file, skip) :
  incomplete final line found on '.../China Survey.csv'

**Comment by JasperHG90** [comment]
This is the same error as #36 and #38. Can you install version 2.1 from the master branch and tell me if that solves the problem? Thanks!

**Comment by shiyaoliu** [comment]
Thanks for the quick response. I downloaded v2.1 and tried it out.

This partially solved the problem. When the questions in qualtrics are in English, the code works now. 

However, when questions and responses contain East Asian languages, say Chinese, there is another error message. This is probably caused by the operation system encoding compatability I guess. Based on my previous experience dealing with East Asian languages in R, it seems that R in Windows needs ANSI encoding, while R in Linux supports Unicode. 

mysurvey <- getSurvey(surveyID = surveys$id[7],
+                       save_dir=getwd())
  |======================================================================================| 100%
Argument `label` must be of same length as numbers of columns in `x`.
 Show Traceback
 
 Rerun with Debug
 Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format

**Comment by JasperHG90** [comment]
The getSurvey() function takes a 'fileEncoding' argument (from the read.csv() function in the utils package). Could you see if one of the encodings provided works for your survey? Thanks!

**Comment by JasperHG90** [comment]
Also: try to run it without inferring data types!

**Comment by JasperHG90** [comment]
Hi Shiyaoliu,

Did you get it to work?

Thanks!

J.

**Comment by shiyaoliu** [comment]
Sorry I have been occupied with some other projects. Will get back to you as soon as I try it out tomorrow.

Thanks.

**Comment by JasperHG90** [comment]
Thanks!

**Comment by JasperHG90** [comment]
Hi Shiyaoliu,

Were you able to test the code?

Thanks!

J.

**Comment by shiyaoliu** [comment]
Hi Jasper,

Sorry for the delayed reply. Unfortunately, adding fileEncoding argument does not seem to work.

However, if I downloaded csv file from Qualtrics and load it with read.csv function (and fileEncoding argument), it works well.

Again, getSurvey works well under my Ubuntu even with Chinese characters. So I suspect that probably somewhere in the getSurveys function there is a dependency on the encoding of the Operating System.

Thank you again for the package!

Sean

Here is the error message.

[cid:image003.jpg@01D300F5.59F91540]

Or the txt version:

> surveys <- getSurveys()
> mysurvey <- getSurvey(surveyID = surveys$id[7], fileEncoding="UTF-8")
  |===============================================================================================| 100%
[data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAYAAADgkQYQAAAAKUlEQVR42mNgQAKi65/9Z8AHQApgmKACrAqxKcBpIkHryFJEstsYiAUAKIxac8kmY3AAAAAASUVORK5CYII=] Show Traceback
 Rerun with Debug
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
In addition: Warning messages:
1: In readLines(file, skip) :
  invalid input found on input connection 'C:/Users/SEANSH~1/AppData/Local/Temp/RtmpKmuk8O/Shenzhen Conjoint - php.csv'
2: In readLines(file, skip) :
  incomplete final line found on 'C:/Users/SEANSH~1/AppData/Local/Temp/RtmpKmuk8O/Shenzhen Conjoint - php.csv'
>
> test <- read.csv("Shenzhen+Conjoint+-+php_July+20%2C+2017_01.05.csv",
+                  fileEncoding = "UTF-8")

**Comment by JasperHG90** [comment]
Hi Sean,

Thanks for your response. I'm going to close this issue for now but will get back to it later when I have some time to dig in.

Thanks for all your help!

J.
