### ISSUE TITLE
Error: package or namespace load failed for ‘qualtRics’:

### ISSUE THREAD

**Issue by avery021** [JasperHG90/qualtRics#44]
I was terminated my R terminal and now I am receive the following error:

Error: package or namespace load failed for ‘qualtRics’:
 .onLoad failed in loadNamespace() for 'qualtRics', details:
  call: yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\n"), 
  error: Scanner error: while scanning a simple key at line 4, column 1could not find expected ':' at line 5, column 1

Any ideas?

**Comment by JasperHG90** [comment]
Do you have a .qualtRics.yml file in your working directory? 

If so, execute `file.edit(".qualtRics.yml")` and fix the layout of your config file.

**Comment by JasperHG90** [comment]
Also, see #28

**Comment by avery021** [comment]
I do have a .qualtRics.yml file. It was running fine until I terminated the R terminal. I reinstalled the qualtRics package and it now works.
