### ISSUE TITLE
Have you seen this error before?

### ISSUE THREAD

**Issue by WChristopherKing** [JasperHG90/qualtRics#45]
Just wondering if you have seen this error/ warning message before.
Do you know what it is?  Do I need to fix it?

Sincerely,

W Christopher King
Polynesian Cultural Center
kingc@polynesia.com

 |=================================================================| 100%
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  invalid input found on input connection 'C:/Users/SDR-RE~1/AppData/Local/Temp/Rtmpgre0N8/Mindshare English v21.csv'
>

**Comment by JasperHG90** [comment]
Thanks for your message. It's likely the same issue as #36 and #41. 

Try installing the version of qualtRics on master and see if the error persists.

```r
install.packages("devtools")
install_github("JasperHG90/qualtRics")
```

**Comment by WChristopherKing** [comment]
Your suggestions worked perfectly!

Mahalo,

Chris King, Polynesian Cultural Center, Hawaii

**Comment by JasperHG90** [comment]
Happy it worked! :-)
