### ISSUE TITLE
Downloading Survey Responses Since last Download

### ISSUE THREAD

**Issue by Delkine** [JasperHG90/qualtRics#47]
Jasper,

I really appreciate the work you have provided for us in this package.  It is a wonderful tool.  It would be a great help if it was possible to have either the datetime or last survey id retained in qualtRics or the .yml at the the end of a download of a specific survey so it could be added to a new getsurvey request.  This would work great with scheduled downloads so only new responses were download.  We collect responses from our surveys daily or weekly and this would allow the process to be automated without downloading all the responses again.

Thanks for considering this.

Delkine

**Comment by JasperHG90** [comment]
Could you not use the 'lastResponseId' parameter for this?

**Comment by Delkine** [comment]
I must not understand how this works.  I thought I had to manually supply ‘lastResponsId’ for that to work.  If I use it will it automatically retain the last id and then use it the next time a download is called?

 

Delkine

**Comment by JasperHG90** [comment]
Sorry for not being clear. You have to supply the response ID. What I mean is that it would be relatively simple for you to implement this yourself. All you'd need to do is set up the following pipeline:

```r
pipeline <- function(surveyID, ...) {
    # 1. Search for 'lastResponseId.rds' in working directory. If it exists, load.
    # 2. If you loaded the last Response ID in step 1, pass it to the 'getSurveys' function, else, run the getSurveys function without this parameter.
    # 3. Take the last responseid from the survey you collected and save it to 'lastResponseId.rds' in your working directory.
    ... rinse and repeat
}
```

This should work fine for what you're trying to do.

Let me know if you need more help with that.

Best,

J.

**Comment by Delkine** [comment]
Jasper,

 

Thank you for your explanation and your offer of further help.  I have tried to do some research on how to use R as you suggest.  I assume the script to create the pipeline could be integrated into a script that runs a download from Qualtrics using your qualtRics package.  I have not be able to find enough information to do it on my own.  Since I am only just beginning to learn R, I’m a bit lost in making the script that would do what you  suggest.  I don’t want to take advantage of your kind offer of help but I am not sure where I can go to learn more about how to create the “pipeline” you suggest would solve our problem in a timely manner.  Can you point me in the right direction?  Any more details about the specifics of your suggestion would also be helpful.

 

I appreciate your willingness to help.

 

Del Nebeker

**Comment by Delkine** [comment]
Jasper,

 

After playing around some more and finding the “tail” function I came up with this.  

…

setwd("c:/Users/del/Qualtrics Data")

lastResponseId.rds <-"R_22VPLzYX75cwrer"

mysurvey <- getSurvey(surveyID = surveys$id[9], 

                      save_dir = "/users/del/Qualtrics Data/",

                      lastResponseId = lastResponseId.rds,

                      verbose=TRUE,

                      uselabels=FALSE,

                      force_request = TRUE)

 

lastResponseId.rds <- tail(mysurvey$ResponseID,1)

 

…

So far it seems to work.  Is this all there is to it?

 

Delkine
