### ISSUE TITLE
Error in registerOptions()

### ISSUE THREAD

**Issue by phoebewong** [JasperHG90/qualtRics#51]
I ran into an error when trying to use registerOptions() to configure my qualtrics account. I tried to both specify the API token and root_url within the function or use the yml file in the working directory. 

The error seems to be related to the assert_that() function. Below is the error.

Error: assert_that: assertion must return a logical value
stop("assert_that: assertion must return a logical value", call. = FALSE)
check_result(res)
see_if(..., env = env)
assertthat::assert_that(!is.na(root_url) | Sys.getenv("QUALTRICS_ROOT_URL") != "", msg = "'root_url' parameter must either be specified in the .qualtRics.yml configuration file or passed to the 'registerOptions' function. To view an example of a configuration file, execute 'qualtRicsConfigFile()'.")

I didn't have an issue of configuring my account when I use the same token and URL
1. the older version of the package with the registerApiKey() function
2. in HTTP requests (with httr package)

Let me know if you need any other info, thanks!

**Comment by phoebewong** [comment]
Just realized that this is documented in the closed #48, and I don't have the error anymore after installing the github version. 

It could be helpful to have the github installation listed as a recommended way of installation in README. Happy to submit a PR if that's helpful. Thanks!

**Comment by JasperHG90** [comment]
Hi Phoebe,

Thanks for your message. I'm planning on submitting the latest version of qualtRics to CRAN today, so this should solve the issue for you and others.

Best,

Jasper.
