### ISSUE TITLE
Set proper rules for file encoding

### ISSUE THREAD

**Issue by JasperHG90** [JasperHG90/qualtRics#58]
In #57 , Erulluvatar set file encoding to be UTF-8. While this is correct for current surveys, legacy files do not use this format. If I remember correctly, it also gives issues for special characters.

Perhaps the best thing to do is to write a little part about it in the README. I can't really test this myself anymore because ironically I don't have a qualtrics account. But if anyone can test special characters for me that'd be great!

**Comment by EruIluvatar** [comment]
Our observation was that the current format uses UTF-8 and legacy uses UTF-8-BOM, so with an addition byte at the beginning of the file.
For reference, you can download the files used in the test: https://github.com/JasperHG90/qualtRics/tree/master/tests/testthat/files
