### ISSUE TITLE
new line in column names breaks readSurvery

### ISSUE THREAD

**Issue by EruIluvatar** [JasperHG90/qualtRics#59]
We found that surveys that use new lines in the questions break the readSurvey function.
The problem is, that read.csv (and read.table as well as the readr library implementation) ignore the `quote = "\""` option when a `skip = 2` or `skip = 3` parameter is set.
As a result the read function slices off the questions row somewhere in the middle when first importing just the table body using `skip`.

Do you have any idea how to circumvent that?
One workaround is to export the csv using the "strip new lines" option in qualtrics.
So if this is the only way to handle the situation, we should put that in the Readme.

**Comment by JasperHG90** [comment]
I'll have a look at this sometime this weekend. Thanks for your comment!

**Comment by EruIluvatar** [comment]
Actually I wonder if we should report this upstream...
I can't think of a reason why this behavior should be intended.

**Comment by EruIluvatar** [comment]
For reference:
https://github.com/tidyverse/readr/issues/772

I have a commit pending where I switch to read_csv instead of read.csv because it fixes other bugs such as working with special characters (unicode).
The same bug exists in base::read.csv though.

**Comment by JasperHG90** [comment]
You have a commit pending? I cannot see it!

**Comment by EruIluvatar** [comment]
Here you go: https://github.com/JasperHG90/qualtRics/pull/62

**Comment by JasperHG90** [comment]
Thanks for this! I'll update the package on CRAN soon
