### ISSUE TITLE
Would you consider submitting your package to rOpenSci onboarding?

### ISSUE THREAD

**Issue by maelle** [JasperHG90/qualtRics#63]
Nice package! Qualtrics is used a lot by scientists so we would be interested in your submitting it to rOpenSci, having such a package in R was even [a topic in our wishlist](https://github.com/ropensci/wishlist/issues/15).

rOpenSci is a community of researchers and developpers developping tools for open science and reproducibility. Some R packages are contributed by staff (e.g. `magick`, `spelling`), others by the community members, which would be the case for your package. Packages undergo peer review before being onboarded, more info [here](https://github.com/ropensci/onboarding).

You should submit if rOpenSci mission appeals to you and if you'd like to receive useful feedback about your package in a friendly environment. After onboarding the package would live in the rOpenSci organization but you would retain admin rights (and you could still pin it, see [my own profile](https://github.com/maelle)). We have a partnership with the Journal of Open Science Software so if you submit the package to us you can choose to have a very short paper.md and get a publication in JOSS.

Ask me any question you may have. ☺

**Comment by JasperHG90** [comment]
Hi Maelle,

Thanks for your comment. This sounds interesting. I'm currently in the middle of my exam period so I need some time to think it through, but I will definitely get back to you on this.

All the best,

Jasper.

**Comment by maelle** [comment]
Fantastic, and good luck for your exams!
