### ISSUE TITLE
qualtrics API Dev!

### ISSUE THREAD

**Issue by lwasser** [JasperHG90/qualtRics#67]
hey @JasperHG90 I just noticed that you submitted this to Ropensci which is super cool! I have an intern currently working on a qualtrics package given as you noted qsurvey is not being actively worked on and actually had a lot of issues under the hood!

https://github.com/earthlab/qtoolkit

I just wondered if we should consider working together in some way! i say this without knowing what precisely qualtRics does compared to qtoolkit. Please let me know if you think this is worth considering! Looping in @1papaya here on this given he's doing the bulk of the work!

**Comment by JasperHG90** [comment]
Hi @lwasser,

Thanks for your message. The scope of this package is restricted to retrieving data using the Qualtrics API. Could you tell me what you want to do with your package?

Best,

Jasper.

**Comment by lwasser** [comment]
Hey @JasperHG90  sure thing! We are retrieving but also working on cleaning up and structuring data in a way that it can be used for analysis. Our main end goal is grabbing data in a way that it is ready to analyze and visualize. We want to make it easier for those doing education research to work with survey data. 

We want to align efforts when possible :) or if possible!

**Comment by JasperHG90** [comment]
Interesting. This is the aim of qualtRics too. I recently implemented some code that downloads survey metadata and converts single-answer multiple choice questions to factors automatically. Perhaps we could Skype? email me at jasperginn@gmail.com

**Comment by lwasser** [comment]
wonderful! ok i'll email you. I am meeting with my colleague who is working on most of the dev right now and we'll get back to you after that meeting! looking forward to chatting @JasperHG90

**Comment by JasperHG90** [comment]
Great! Looking forward
