### ISSUE TITLE
Thoughts on supporting other API functions?

### ISSUE THREAD

**Issue by ryantsullivan** [JasperHG90/qualtRics#68]
Hey @JasperHG90,

Thanks so much for the awesome package. I use it daily and it has saved me a ton of time. I was wondering if you had any interest in expanding the core functions of the package? I have been mulling over creating some functions for creating mailing lists, adding embedded data to surveys or updating embedded data and scheduling distributions. 

I could either put these in a separate package or if your interested could submit pull requests as I develop them. 

Let me know what you think.

-RS

**Comment by JasperHG90** [comment]
Hi Ryan,

Thanks for your message. I'm glad you like the package.

Short answer: yes. I always thought of this package as a way to standardise the import of Qualtrics data. That includes things like mailing lists etc. Just so happens that I have limited time and I thought that properly importing survey data was the most important. 

I'm happy with any contribution that **retrieves** data. Feel free to submit pull requests for additional functions. Make sure you check out [utils.R](https://github.com/JasperHG90/qualtRics/blob/master/R/utils.R) for helper functions you could use and that you properly document your work.

Let me know if you have any questions!

Best,

Jasper.

**Comment by ryantsullivan** [comment]
@JasperHG90 

Thanks. I will send a few PRs hopefully soon. I need to take some of the functions I have written and document them better and integrate your utility functions. I will start out with some easier data retrieval functions and move on from there. 

So to clarify,  you have no interest in functions that would allow the user of the package to insert data into Qualtrics? I have previously used the Put Embedded Data, Update Responses and Import Responses calls from Qualtrics. They also have a newer Insert Embedded Data call.

**Comment by JasperHG90** [comment]
Currently, functions that pull data into R have a priority for me. Of course if there is demand for the functionality you mentioned we could implement that.
