### ISSUE TITLE
Error in nchar(y) : invalid multibyte string, element 1 > 

### ISSUE THREAD

**Issue by OldMortality** [JasperHG90/qualtRics#72]
Hi,

[edor1.zip](https://github.com/JasperHG90/qualtRics/files/1790817/edor1.zip)

I have exported a csv file from qualtrix, but when I try to load it into R, I get an error:

library('qualtRics')
s <- readSurvey('/Users/../Documents/edor1.csv')

Error in nchar(y) : invalid multibyte string, element 1

There is no error with read.csv. I have read issue 36, but I do not understand how that may solve my problem. The csv file is in the attached zip.

Many thanks for your attention.

**Comment by JasperHG90** [comment]
Hi,

Columns like these are the issue.

<img width="679" alt="spec" src="https://user-images.githubusercontent.com/8079803/37148689-a68703d8-22cb-11e8-8fe2-68de49b24631.png">

Try to remove special characters in the columns. I'm looking for a way to avoid these sort of problems regardless of special characters, but that will be implemented in a later version.

**Comment by JasperHG90** [comment]
Could you tell me if/whether you solved the issue? Thanks!

**Comment by OldMortality** [comment]
Yes, thank you. It worked.
