### ISSUE TITLE
example data, metadata

### ISSUE THREAD

**Issue by rubenarslan** [JasperHG90/qualtRics#74]
Hi, I was wondering whether the metadata you add via Qualtrics is something I could support in my [codebook](https://github.com/rubenarslan/codebook) package. I already support my own survey software (I use the semantics used in haven, so variable, value, missing labels as attributes). I don't have a Qualtrics account though, so I can't easily check what data from your package looks like. Could you maybe add example data to the package, so that I can run e.g. `metadata` or `readSurvey` and see whether this would work?

**Comment by JasperHG90** [comment]
Hi Ruben,

Thanks for your message. Please email me at jasperginn@gmail.com. I'd be happy to give you API access to my dev account for a couple of days so you can play around with it.

Best,

Jasper.

**Comment by JasperHG90** [comment]
Send sample file by email and added metadata example file. See examples under ?qualtRics::metadata
