### ISSUE TITLE
With API token correct, but authentication still failed. 

### ISSUE THREAD

**Issue by jiashen85** [JasperHG90/qualtRics#8]
Hi Jasper,

I started to play your package. I used registerApiKey function to register my API and made sure it returned 'TRUE'. However, when i followed steps on vignette and tried to download one specific survey with its survey ID found in the account setting-Qualtrics IDs. It returned the below error: 

Query returned status "401 - Unauthorized". Please check your code.

Can you add a user credential argument in your getsurveys functions.  Thank you!

**Comment by JasperHG90** [comment]
Hi,


Thanks for your email.


1) Make sure you have copied the right key from the menu and that you have API access.

2) Make sure you are the survey owner. If you are NOT the owner and you do not have explicit admin rights, you cannot export data.

3) Use 'getSurveys()' to get a list of surveys on your account and try it with one of the IDs listed in that data frame.


Let me know if that works!


Also: I'd appreciate it if you would ask these questions on GitHub (under 'Issues'). That way, other people can use solutions if they encounter a similar problem!


All the best,


Jasper.

________________________________
Van: jiashen85 <notifications@github.com>
Verzonden: woensdag 14 december 2016 03:48:54
Aan: JasperHG90/qualtRics
Onderwerp: [JasperHG90/qualtRics] With API token correct, but authentication still failed. (#8)


Hi Jasper,

I started to play your package. I used registerApiKey function to register my API and made sure it returned 'TRUE'. However, when i followed steps on vignette and tried to download one specific survey with its survey ID found in the account setting-Qualtrics IDs. It returned the below error:

Query returned status "401 - Unauthorized". Please check your code.

What could be possibly wrong? Can you shed some light on it? Thank you!

-

**Comment by jiashen85** [comment]
Hi Jasper,

Thanks for the clarification. I'm not the owner. Maybe that's why I can't
export data.

**Comment by JasperHG90** [comment]
Ask the owner to give you admin rights and then try again!
